name: Publish Docker image

on:
  push:
    branches:
      - 'main'
env:
 dtown12/dtown-1: webserver

jobs:
  build-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Build the Docker image
        run: docker build -t webserver .
        
      - name: Run container from image
        run: docker run -d --name httpd -p 80:80 webserver
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dtown12
          password: ${{ secrets.DTOWN12 }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: dtown12/dtown-1
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DTOWN12 }}/dtown-1:latest      
            ${{ steps.meta.outputs.tags }}
