name: Publish Docker image

on:
  push:
    branches: [main]
    tags:
      - "v*.*.*"

jobs:
 push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: dtown12/dtown-1
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dtown12
          password: ${{ secrets.DTOWN12 }}
            
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./P4
          file: ./Dockerfile
          push: true
          tags: |
            dtown12/dtown-1:latest      
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
